# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos7"
  config.vm.box_version = "3.1.4"
  config.vm.provision "ansible", run: "always" do |ansible|
    ansible.playbook = "zfs.yml"
  end
end
